"""Add reminder field to Task model

Revision ID: 42951a3c068f
Revises: 
Create Date: 2024-07-05 14:39:08.274558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42951a3c068f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminder_time', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('reminder_time')

    # ### end Alembic commands ###
